# Generated by Django 4.1.6 on 2023-02-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.PositiveIntegerField()),
                ('contribution_interval', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10)),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('interval', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('Employed', 'Employed'), ('Business Owner', 'Business Owner'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_amount', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.collecttable')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.contribution')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='esusu_app.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='esusu_app.user'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_belong_to', to='esusu_app.group'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='esusu_app.user'),
        ),
        migrations.AddField(
            model_name='collecttable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to='esusu_app.group'),
        ),
        migrations.AddField(
            model_name='collecttable',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contributions', to='esusu_app.user'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.member')),
            ],
        ),
    ]
