# Generated by Django 4.1.6 on 2023-02-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('MARRIED', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Single Mom', 'Single Mom')], default='Single', max_length=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(max_length=16),
        ),
    ]
