# Generated by Django 4.1.6 on 2023-02-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0003_user_gender_user_marital_status_alter_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_contributions', to='esusu_app.user'),
            preserve_default=False,
        ),
    ]
