# Generated by Django 4.1.6 on 2023-02-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0004_contribution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecttable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='esusu_app.user'),
            preserve_default=False,
        ),
    ]
