# Generated by Django 4.1.6 on 2023-02-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0005_collecttable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members_contributions', to='esusu_app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_contributions', to='esusu_app.user'),
        ),
    ]
