# Generated by Django 4.1.6 on 2023-02-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0006_groupadmin_member_alter_groupadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecttable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='member',
        ),
        migrations.AlterField(
            model_name='groupadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esusu_app.user'),
        ),
    ]
