# Generated by Django 4.1.6 on 2023-02-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusu_app', '0007_remove_collecttable_user_remove_contribution_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadmin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esusu_app.user'),
        ),
    ]
